from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from typing import List
from audio_api.models.audio import TranscriptSegment


class GoogleDocsService:
    def __init__(self, access_token: str):
        self.creds = Credentials(token=access_token)

    def create_transcript_doc(self, title: str, transcript: List[TranscriptSegment]) -> str:
        try:
            service = build('docs', 'v1', credentials=self.creds)
            drive_service = build('drive', 'v3', credentials=self.creds)
            doc_body = {'title': f"[VoiceDiary] {title}"}
            doc = service.documents().create(body=doc_body).execute()
            document_id = doc.get('documentId')
            requests = [{
                'insertText': {
                    'location': {'index': 1},
                    'text': f"TRANSCRIPT: {title}\nGenerated by VoiceDiary\n\n"
                }
            }]
            full_text = ""
            for seg in transcript:
                time_str = f"[{int(seg.start // 60):02d}:{int(seg.start % 60):02d}]"
                full_text += f"{time_str} {seg.text}\n"
            requests.append({
                'insertText': {
                    'location': {'index': 1},
                    'text': full_text
                }
            })
            service.documents().batchUpdate(
                documentId=document_id,
                body={'requests': requests}
            ).execute()
            file_info = drive_service.files().get(
                fileId=document_id,
                fields='webViewLink'
            ).execute()
            return file_info.get('webViewLink')

        except Exception as e:
            raise RuntimeError(f"Google Docs API Error: {str(e)}")