import re

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from typing import List, Dict
from audio_api.models.audio import TranscriptSegment


class GoogleDocsService:
    def __init__(self, access_token: str):
        self.creds = Credentials(token=access_token)

    def create_transcript_doc(self, title: str, transcript: List[TranscriptSegment]) -> Dict[str, str]:
        try:
            service = build('docs', 'v1', credentials=self.creds)
            drive_service = build('drive', 'v3', credentials=self.creds)
            doc_body = {'title': f"[VoiceDiary] {title}"}
            doc = service.documents().create(body=doc_body).execute()
            document_id = doc.get('documentId')
            requests = [{
                'insertText': {
                    'location': {'index': 1},
                    'text': f"TRANSCRIPT: {title}\nGenerated by VoiceDiary\n\n"
                }
            }]
            full_text = ""
            for seg in transcript:
                time_str = f"[{int(seg.start // 60):02d}:{int(seg.start % 60):02d}]"
                full_text += f"{time_str} {seg.text}\n"
            requests.append({
                'insertText': {
                    'location': {'index': 1},
                    'text': full_text
                }
            })
            service.documents().batchUpdate(
                documentId=document_id,
                body={'requests': requests}
            ).execute()
            file_info = drive_service.files().get(
                fileId=document_id,
                fields='webViewLink'
            ).execute()
            return {
                'document_id': document_id,
                'webViewLink': file_info.get('webViewLink')
            }

        except Exception as e:
            raise RuntimeError(f"Google Docs API Error: {str(e)}")

    def get_document_content(self, doc_id: str) -> str:
        try:
            service = build('docs', 'v1', credentials=self.creds)
            document = service.documents().get(documentId=doc_id).execute()
            content = document.get('body').get('content')
            return self._read_structural_elements(content)
        except Exception as e:
            raise RuntimeError(f"Failed to read Google Doc: {str(e)}")

    def _read_structural_elements(self, elements):
        text = ''
        for value in elements:
            if 'paragraph' in value:
                elements = value.get('paragraph').get('elements')
                for elem in elements:
                    if 'textRun' in elem:
                        text += elem.get('textRun').get('content')
            elif 'table' in value:
                pass
        return text

    def parse_transcript_from_text(self, raw_text: str) -> List[TranscriptSegment]:
        segments = []
        pattern = re.compile(r'\[(\d{1,2}):(\d{2})\]\s*(.*?)(?=\[\d{1,2}:\d{2}\]|$)', re.DOTALL)
        matches = pattern.findall(raw_text)
        for i, match in enumerate(matches):
            minutes, seconds, content = match
            start_seconds = int(minutes) * 60 + int(seconds)
            text = content.strip()
            if "TRANSCRIPT:" in text or "Generated by" in text:
                continue
            segments.append(TranscriptSegment(
                start=float(start_seconds),
                end=0.0,
                text=text
            ))
        for i in range(len(segments) - 1):
            segments[i].end = segments[i + 1].start
        if segments:
            segments[-1].end = segments[-1].start + 2.0

        return segments