from io import BytesIO
from typing import List
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from audio_api.models.audio import TranscriptSegment

class PdfService:
    @staticmethod
    def create_transcript_pdf(title: str, transcript: List[TranscriptSegment]) -> BytesIO:
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        # Tiêu đề
        story.append(Paragraph(title, styles['Title']))
        story.append(Spacer(1, 12))
        story.append(Paragraph("Generated by VoiceDiary", styles['Normal']))
        story.append(Spacer(1, 24))

        # Style cho đoạn hội thoại
        dialog_style = ParagraphStyle(
            'Dialog',
            parent=styles['Normal'],
            spaceAfter=10,
            leading=14
        )
        for seg in transcript:
            time_str = f"[{int(seg.start // 60):02d}:{int(seg.start % 60):02d}]"
            text = f"<b>{time_str} {seg.speaker}:</b> {seg.text}"
            story.append(Paragraph(text, dialog_style))
        doc.build(story)
        buffer.seek(0)
        return buffer