# src/audio_api/services/word_service.py
from io import BytesIO
from typing import List

from docx import Document
from docx.shared import RGBColor

from audio_api.models.audio import TranscriptSegment


class WordService:
    @staticmethod
    def create_transcript_docx(title: str, transcript: List[TranscriptSegment]) -> BytesIO:
        document = Document()
        document.add_heading(f"[VoiceDiary] {title}", 0)
        document.add_paragraph('Generated by VoiceDiary App').italic = True
        document.add_paragraph('')
        for seg in transcript:
            minutes = int(seg.start // 60)
            seconds = int(seg.start % 60)
            time_str = f"[{minutes:02d}:{seconds:02d}]"
            p = document.add_paragraph()
            runner_time = p.add_run(time_str)
            runner_time.bold = True
            runner_time.font.color.rgb = RGBColor(0, 51, 102)
            p.add_run(f" {seg.speaker.lower()}: {seg.text}")
        file_stream = BytesIO()
        document.save(file_stream)
        file_stream.seek(0)
        return file_stream